FROM node:20-alpine AS base
RUN apk add --no-cache libc6-compat
WORKDIR /app

# Install dependencies
COPY package.json package-lock.json ./
RUN npm ci --ignore-scripts --legacy-peer-deps

# Copy application files
COPY . .

# Run postinstall
RUN npm run postinstall

ENV NODE_ENV=production

# Build-time-only placeholders so Next's "collect page data" step doesn't crash on
# eager client/config creation. Real values are injected at container runtime via --env-file.
ARG BUILD_PLACEHOLDER=build-placeholder-not-a-real-secret
ENV SUPABASE_URL=https://build-placeholder.supabase.co
ENV SUPABASE_SERVICE_ROLE_KEY=${BUILD_PLACEHOLDER}
ENV VAPI_MASTER_KEY=${BUILD_PLACEHOLDER}
ENV WHISPEY_MASTER_KEY=${BUILD_PLACEHOLDER}

# Real value required — gets baked into the client bundle by Next.js at build time.
ARG NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
ENV NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
RUN if [ -z "$NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY" ]; then echo "ERROR: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY build-arg is empty"; exit 1; fi
RUN echo "Clerk key prefix: $(echo $NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY | cut -c1-8)  length: ${#NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}"

# Every other NEXT_PUBLIC_* var read anywhere in src/ — Next.js inlines these
# into the client bundle at `next build` time too, same as the Clerk key above.
# Passing them only via --env-file at container start (like the server-only
# secrets below) never reaches client code — this was the actual cause of
# "Create Agent" always showing disabled regardless of the runtime whitelist.
ARG NEXT_PUBLIC_AGENT_CREATION_WHITELIST
ENV NEXT_PUBLIC_AGENT_CREATION_WHITELIST=${NEXT_PUBLIC_AGENT_CREATION_WHITELIST}
ARG NEXT_PUBLIC_POSTHOG_BLACKLIST
ENV NEXT_PUBLIC_POSTHOG_BLACKLIST=${NEXT_PUBLIC_POSTHOG_BLACKLIST}
ARG NEXT_PUBLIC_POSTHOG_KEY
ENV NEXT_PUBLIC_POSTHOG_KEY=${NEXT_PUBLIC_POSTHOG_KEY}
ARG NEXT_PUBLIC_POSTHOG_HOST
ENV NEXT_PUBLIC_POSTHOG_HOST=${NEXT_PUBLIC_POSTHOG_HOST}
ARG NEXT_PUBLIC_SONIC_LINKER_ORG_ID
ENV NEXT_PUBLIC_SONIC_LINKER_ORG_ID=${NEXT_PUBLIC_SONIC_LINKER_ORG_ID}
ARG NEXT_PUBLIC_APP_URL
ENV NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
ARG NEXT_PUBLIC_MONITORING_SERVICE_BASE_URL
ENV NEXT_PUBLIC_MONITORING_SERVICE_BASE_URL=${NEXT_PUBLIC_MONITORING_SERVICE_BASE_URL}
ARG NEXT_PUBLIC_MONITORING_AGENT_BASE_URL
ENV NEXT_PUBLIC_MONITORING_AGENT_BASE_URL=${NEXT_PUBLIC_MONITORING_AGENT_BASE_URL}
ARG NEXT_PUBLIC_PYPEAI_API_URL
ENV NEXT_PUBLIC_PYPEAI_API_URL=${NEXT_PUBLIC_PYPEAI_API_URL}
ARG NEXT_PUBLIC_DISPOSITION_PROJECTS
ENV NEXT_PUBLIC_DISPOSITION_PROJECTS=${NEXT_PUBLIC_DISPOSITION_PROJECTS}
ARG NEXT_PUBLIC_METABASE_URL
ENV NEXT_PUBLIC_METABASE_URL=${NEXT_PUBLIC_METABASE_URL}
ARG NEXT_PUBLIC_FEEDBACK_URL
ENV NEXT_PUBLIC_FEEDBACK_URL=${NEXT_PUBLIC_FEEDBACK_URL}
ARG NEXT_PUBLIC_X_API_KEY
ENV NEXT_PUBLIC_X_API_KEY=${NEXT_PUBLIC_X_API_KEY}
ARG NEXT_PUBLIC_API_BASE_URL_CAMPAIGN
ENV NEXT_PUBLIC_API_BASE_URL_CAMPAIGN=${NEXT_PUBLIC_API_BASE_URL_CAMPAIGN}
ARG NEXT_PUBLIC_LIVEKIT_URL
ENV NEXT_PUBLIC_LIVEKIT_URL=${NEXT_PUBLIC_LIVEKIT_URL}
ARG NEXT_PUBLIC_API_BASE_URL_SEND_CALL_LOG_LAMBDA
ENV NEXT_PUBLIC_API_BASE_URL_SEND_CALL_LOG_LAMBDA=${NEXT_PUBLIC_API_BASE_URL_SEND_CALL_LOG_LAMBDA}
ARG NEXT_PUBLIC_API_BASE_URL_OLD_CAMPAIGN
ENV NEXT_PUBLIC_API_BASE_URL_OLD_CAMPAIGN=${NEXT_PUBLIC_API_BASE_URL_OLD_CAMPAIGN}
ARG NEXT_PUBLIC_REPROCESS_API_BASE_URL
ENV NEXT_PUBLIC_REPROCESS_API_BASE_URL=${NEXT_PUBLIC_REPROCESS_API_BASE_URL}

# Build the production bundle
RUN npm run build

# Create a non-root user
RUN addgroup --system --gid 1001 nodejs && \
    adduser --system --uid 1001 nextjs && \
    chown -R nextjs:nodejs /app

USER nextjs

EXPOSE 3000

ENV PORT=3000

CMD ["npm", "run", "start"]
