sonar.projectKey=Whispey
sonar.projectName=Whispey

sonar.sources=src
sonar.tests=__tests__

sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Disable SCM blame to significantly reduce report size
sonar.scm.disabled=true

sonar.exclusions=\
  **/node_modules/**,\
  **/.next/**,\
  **/coverage/**,\
  **/*.d.ts,\
  **/components/ui/**,\
  **/types/**,\
  **/*.stories.*,\
  **/app/docs/**

sonar.coverage.exclusions=\
  **/__tests__/**,\
  **/node_modules/**,\
  **/.next/**,\
  **/components/ui/**
